name: Auto approve

on:
  pull_request:
    paths-ignore:
      - 'myfiles/**'

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
