---
name: Default workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  failing:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  conclustion:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - failing
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - run: |
          echo "$WORKFLOW_CONCLUSION"
