name: Pull request trigger

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - master

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: get_sha1
        run: echo $GITHUB_SHA1
