name: terraform
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "::add-path:: $HOME/.tfenv/bin"
      - run: echo "$PATH"
      - run: terraform -version
      - run: tfenv install 0.12.24
      - run: terraform -version
