name: terraform
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tfenv
        run: |
          sudo git clone https://github.com/tfutils/tfenv.git /usr/local/tfenv
          sudo ln -sf /usr/local/tfenv/bin/* /usr/local/bin
      - run: which terraform
      - run: terraform -version
      - run: |
          $HOME/.tfenv/bin/tfenv install 0.12.23
          $HOME/.tfenv/bin/tfenv use 0.12.23
      - run: $HOME/.tfenv/bin/terraform -version
      - run: |
          sudo bash -c 'echo "echo It works!" > /usr/local/bin/works_or_not'
          sudo chmod a+x /usr/local/bin/works_or_not
          works_or_not
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
